server:
  port: 9527
spring:
  application:
    name: cloud-gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true   #开启从注册中心动态创建路由的功能，利用微服务名进行路由
      routes:
        #- id: payment_routh #路由的ID，没有固定规则但要求唯一，建议配合服务名
          #uri: http://localhost:8001   #匹配后提供服务的路由地址
          #uri: lb://cloud-payment-service #匹配后提供服务的路由地址（lb是load balance的缩写）
          #predicates:
            #- Path=/payment/get/**   #断言,路径相匹配的进行路由

        - id: payment_routh2
          #uri: http://localhost:8001
          uri: lb://cloud-payment-service #匹配后提供服务的路由地址
          predicates:
            - Path=/payment/lb/**   #断言,路径相匹配的进行路由
            #- After=2021-02-04T11:15:42.187+08:00[Asia/Shanghai] #可以做版本控制，（比如这个路由什么时候有效）
            #- Cookie=username,atguigu #curl localhost:9527/payment/lb --cookie "username=atguigu" 用curl测试
            #- Header=X-Request-Id, \d+ #header头要匹配定义的正则表达式  curl http://localhost:8080  -H "X-Request-Id:666666"
            #- Method=GET #访问方式要是GET才行


eureka:
  instance:
    hostname: cloud-gateway-service
  client:
    service-url:
      register-with-eureka: true
      fetch-registry: true
      defaultZone: http://eureka7001.com:7001/eureka
