server:
  port: 80

spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource          #当前数据源操作类型
    driver-class-name: org.gjt.mm.mysql.Driver            #mysql的驱动包
    url: jdbc:mysql://localhost:3306/db2021?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=UTC
    username: root
    password: 123456
  application:
    name: cloud-order-service

eureka:
  instance:
    prefer-ip-address: true #注册服务的时候使用服务的IP地址进行注册
  client:
    register-with-eureka: true
    fetchRegistry: true
    service-url:
      #defaultZone: http://eureka7001.com:7001/eureka,http://eureka7002.com:7002/eureka  #集群版
      defaultZone: http://localhost:7001/eureka