#构建微服务的一个子服务（五步）
#1.建module
#2.改pom
#3.写yml
#4.主启动
#5.业务类

server:
  port: 8001

spring:
  application:
    name: cloud-payment-service                           #当前服务起个名称
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource          #当前数据源操作类型
    driver-class-name: org.gjt.mm.mysql.Driver            #mysql的驱动包
    url: jdbc:mysql://localhost:3306/db2021?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=UTC
    username: root
    password: 123456

mybatis:
  mapperLocations: classpath:mapper/*.xml                 #springboot整合mybatis，保证springboot可以扫描到mapper
  type-aliases-package: com.atguigu.springcloud.entities  #所有Entity别名类所在包

eureka:
  instance:
    prefer-ip-address: true #注册服务的时候使用服务的IP地址进行注册
    instance-id: payment8001
    lease-renewal-interval-in-seconds: 1 #Eureka客户端向服务端发送细条的时间间隔，单位为秒（默认是30秒）
    lease-expiration-duration-in-seconds: 2 #Eureka服务端在收到最后一次心跳后等待时间上线，单位为秒（默认是90秒），超时将剔除服务
  client:
    register-with-eureka: true                            #表示是否将自己注册金EurekaServer默认为true
    fetchRegistry: true                                   #是否从eurekaServer抓取已有的注册信息，默认为true，单节点无所谓，集群必须设置为true才能配合ribbon使用负载均衡
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka,http://eureka7002.com:7002/eureka  #集群版
      #defaultZone: http://eureka7001.com:7001/eureka #单机版